### PR TITLE
update apollo-server-express and refactor server function

### PR DESCRIPTION
**Pull request by RobDolares**
Related issue: https://github.com/open-cluster-management/backlog/issues/15869
Signed-off-by: rhowingt@redhat.com <rhowingt@redhat.com>

### CODE REVIEW

**Comment by RobDolares** [comment]
@ChunxiAlexLuo - Could you help with this?
Underlying issue is [this CVE](https://github.com/open-cluster-management/backlog/issues/15869) - Trying to update `apollo-server-express`, as v2 has the vulnerability.

fyi @KevinFCormier

**Comment by ChunxiAlexLuo** [comment]
> @ChunxiAlexLuo - Could you help with this?
> Underlying issue is [this CVE](https://github.com/open-cluster-management/backlog/issues/15869) - Trying to update `apollo-server-express`, as v2 has the vulnerability.
> 
> fyi @KevinFCormier

Ok, I can take a look at it

**Comment by ChunxiAlexLuo** [comment]
Tried many ways last week but still have some small issues with this updating. Will do further investigation later.

**Comment by RobDolares** [comment]
@ChunxiAlexLuo - no worries.  Oddly enough, the image scan passed and related issue closed.

We can revisit this work if future scans fail, and would be nice to get to latest major version.  Thanks again for looking into this.

Closing PR for hygiene purposes.

**Pull request closed without merging**
