### PR TITLE
backport issue 13595 to 2.2

### PR DESCRIPTION
**Pull request by gparvin**
Signed-off-by: Gus Parvin <gparvin@redhat.com>
This is my attempt at backporting https://github.com/open-cluster-management/backlog/issues/13595 to 2.2.
Goal is for delivery into `2.2.6`

### CODE REVIEW

**Review by ChunxiAlexLuo — APPROVED** [review]
/lgtm

**Comment by gparvin** [comment]
I had to undo the change to `package-lock.json` file in pr https://github.com/open-cluster-management/grc-ui-api/pull/145.  I certainly don't really understand why/how to manage that file and undoing it fixed the build issue.

**Pull request merged**
